In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn.preprocessing import StandardScaler, OneHotEncoder, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score



In [114]:
path=Path("/content/Crop_recommendation.csv")
df=pd.read_csv(path)
df.head(3)

,N,P,K,temperature,humidity,ph,rainfall,label
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice


In [118]:
Z=[1,2,4]
def softmax(Z):
  exp_z=np.exp(Z-max(Z,axis=1,keepdims=True))
  return exp_z/np.sum(exp_z,axis=1,keepdims=True)


In [120]:
x=df[['N','P','K']].to_numpy()
y=df['label'].to_numpy()[:,np.newaxis]

In [121]:
from sklearn.preprocessing import add_dummy_feature
x_oness=add_dummy_feature(x)

In [127]:
m,n=x_oness.shape
k=22
rng = np.random.default_rng(seed=123)
Theta = rng.standard_normal(size=(n, 22))

In [130]:
z=x_oness@Theta
z.shape

(2200, 22)

In [131]:
z

array([[ 128.33672504,   43.60141435,   79.41840324, ..., -144.73809041,
          23.37301837,   32.34619345],
       [ 108.97042689,   29.16580884,   74.06843025, ..., -145.23358228,
          -4.76672753,   55.51604213],
       [  73.76794413,    0.77773422,   56.27478841, ..., -113.16176875,
         -39.19177553,   54.51398584],
       ...,
       [ 171.8592099 ,   90.15558082,   97.24097232, ..., -172.23331593,
          89.27443253,   19.22624508],
       [ 172.74733821,   86.82105402,   97.73625105, ..., -171.6445607 ,
          85.30023832,   16.92612529],
       [ 160.38277162,   83.96618722,   87.59461722, ..., -147.66131537,
          90.7993394 ,    0.94027914]])

In [138]:
exp_z=np.exp(z-np.max(z,axis=1,keepdims=True))
exp_z/np.sum(np.exp(exp_z))

array([[9.08593283e-052, 1.43976519e-088, 5.16906864e-073, ...,
        2.30931951e-170, 2.36162488e-097, 1.86299350e-093],
       [1.73518176e-062, 3.80749834e-097, 1.20670309e-077, ...,
        6.91745777e-173, 6.98114119e-112, 1.05779288e-085],
       [1.99996133e-058, 3.99738705e-090, 5.05639038e-066, ...,
        1.31364734e-139, 1.75080860e-107, 8.69228101e-067],
       ...,
       [7.53178887e-046, 2.47435995e-081, 2.95535264e-078, ...,
        2.75050796e-195, 1.02514439e-081, 3.88368285e-112],
       [1.10254208e-045, 5.30987263e-083, 2.92074703e-078, ...,
        2.98465315e-195, 1.16038534e-083, 2.34478076e-113],
       [1.03872154e-033, 6.74835943e-067, 2.54100389e-065, ...,
        1.71653226e-167, 6.26323184e-064, 5.90887048e-103]])

In [172]:
def softmax(z):
  exp_z=np.exp(z-np.max(z,axis=1,keepdims=True))
  return exp_z/np.sum(exp_z,axis=1,keepdims=True)


In [140]:
y.shape

(2200, 1)

In [141]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse_output=False)
y_encoded=ohe.fit_transform(y)

In [142]:
y_encoded.shape

(2200, 22)

In [173]:
n_epoches=10000
lr=0.1
m,n=x_oness.shape
k=22
rng = np.random.default_rng(seed=123)
theta = rng.standard_normal(size=(n, 22))
for epoch in range(n_epoches):
  z=x_oness@theta
  h=softmax(z)
  gradient=1/m*x_oness.T@(h-y_encoded)
  theta=theta-lr*gradient
theta.shape




(4, 22)

In [174]:
x_testt.shape

(1, 4)

In [175]:
x_testt=np.array([[1,20.7,38.3,42.4]])
z_testt=x_testt@theta
h_testt=softmax(z_testt)
y_pred=np.argmax(h_testt,axis=1)
y_pred

array([12])

In [177]:
df['label'].iloc[12]

'rice'

In [176]:
h_testt

array([[2.16850483e-033, 2.46166356e-057, 8.57180265e-114,
        8.11023529e-038, 6.45335344e-004, 5.14615210e-126,
        1.09796246e-218, 8.56763920e-017, 2.10879523e-046,
        1.20418771e-117, 1.02781134e-108, 5.40922603e-143,
        9.99174745e-001, 6.03680836e-070, 1.53762511e-074,
        2.02567649e-081, 1.82694820e-066, 1.69370892e-004,
        3.95226318e-101, 1.05488109e-005, 1.18348787e-049,
        5.29452188e-096]])